### ISSUE TITLE
failed to get trace with id: Status: 404 Not Found Body: 404 page not found

### ISSUE THREAD

**Issue by satwika007** [dgzlopes/foo-bar-demo#1]
Followed the exact same steps as in README.md file. But unable to view traces on grafana

**Comment by dgzlopes** [comment]
Hi @satwika007! Thanks for creating the issue :) 

Yup, looks like I bumped the OpenTelemetry version, and something broke. Meanwhile, I've removed that commit.

Sorry for the inconvenience... If you remove the repo and redo the steps, everything should work.
