### ISSUE TITLE
Typo in Associated Blog

### ISSUE THREAD

**Issue by Mkrummz** [dgzlopes/foo-bar-demo#3]
in this blog https://grafana.com/blog/2021/05/04/get-started-with-distributed-tracing-and-grafana-tempo-using-foobar-a-demo-written-in-python/

the docker run command has a slight typo. 

blog: 
docker run -i --network=foobardemo_default loadimpact/k6 run --quiet - <example.js

what is should be: 
docker run -i --network=foobar-demo_default loadimpact/k6 run --quiet - <example.js

**Comment by dgzlopes** [comment]
Hey! Thanks, good catch :)

I have fixed the blog post.
